### ISSUE TITLE
Is it possible to colorize ribbons?

### ISSUE THREAD

**Issue by onrea** [digitalcraftsman/hugo-hikari-theme#7]
I mean:

```
First ribbon: blue
2nd: red
3rd: blues
4th: red
next one: blue
...
```

Is it possible to have different colors on ribbons?

**Comment by digitalcraftsman** [comment]
Hello @onrea,

your request is very specific, especially if you want to define the ribbon colors from the config file. However, I added an option for an easy inclusion of custom stylesheets. Add the following variable to your `config.toml` and link your custom stylesheet relative to the `static` folder:

``` toml
[params]
    custom_css = ["path/to/custom.css"]
```

Now let's add some CSS rules to customize each ribbon:

``` css
.posts li:nth-child(N) .p-wrap {
    background-color: red;
    color: green;
}

.posts li:nth-child(N) .p-wrap time {
    color: green;
}
```

Replace the `N` in `:nth-child(N)` with the integer of the nth ribbon, 1 for the first etc. You have to copy this snippet for each ribbon you want to style. If no custom colors are defined the stylesheet will default to purple.

Cheers, 
Digitalcraftsman
